# requirements for angelman project
name: angelman
dependencies:
  - ipython=7.31.1
  - python=3.9.12
  - numpy=1.22.3
  - pandas=1.4.2
  - scipy=1.7.3
  - matplotlib-base=3.5.1
  - scikit-learn=1.0.2
